const speakers = [
  {
    name: "Folasade Femi-Lawal",
    title: "Country Manager, West Africa,",
    company: "Mastercard",
    image: "assets/images/speakers/folasade.jpg",
    linkedIn: "#",
  },
  {
    name: "Kehinde Ogundare",
    title: "Country Manager, Nigeria,",
    company: "Zoho",
    image: "assets/images/speakers/kehinde-ogundare.jpg",
    linkedIn: "#",
  },
  {
    name: "Tolu Alabi",
    title: "CEO",
    company: "Cleva Banking",
    image: "assets/images/speakers/tolu-alabi.jpg",
    linkedIn: "#",
  },
  {
    name: "Tolulope A. Adeyinka",
    title: "Fintech Business Development Lead,",
    company: "Mastercard, West Africa",
    image: "assets/images/speakers/tolulope-adeyinka.jpg",
    linkedIn: "#",
  },
  {
    name: "Yewande Adewusi",
    title: "Chief Operating Officer,",
    company: "Alitheia Capital",
    image: "assets/images/speakers/yewande-adewusi.jpg",
    linkedIn: "#",
  },
  {
    name: "Dr Dotun Olowoporoku",
    title: "Managing Partner,",
    company: "Ventures Platform",
    image: "assets/images/speakers/dotun-olowo.jpg",
    linkedIn: "#",
  },
  {
    name: "Satoshi Shinada",
    title: "Partner,",
    company: "Verod-Kepple Africa Ventures",
    image: "assets/images/speakers/satoshi-shinada.jpg",
    linkedIn: "#",
  },
  {
    name: "Olu Oyinsan",
    title: "Managing Partner,",
    company: "Oui Capital",
    image: "assets/images/speakers/olu-oyinsan.jpg",
    linkedIn: "#",
  },
  {
    name: "Babatunde Obadero",
    title: "Chief Executive Officer,",
    company: "Zitra",
    image: "assets/images/speakers/babatunde-obadero.jpg",
    linkedIn: "#",
  },
  {
    name: "Babajide Duroshola",
    title: "General Manager, Nigeria,",
    company: "M-Kopa",
    image: "assets/images/speakers/babajide-duroshola.jpg",
    linkedIn: "#",
  },
  {
    name: "Fola Olatunji-David",
    title: "Founding Partner,",
    company: "Kickoff Africa",
    image: "assets/images/speakers/fola-olatunji.png",
    linkedIn: "#",
  },
  {
    name: "Olawale Samuel",
    title: "CEO,",
    company: "Axia Africa",
    image: "assets/images/speakers/olawale-olakanmi.jpg",
    linkedIn: "#",
  },
  {
    name: "Sunil Natraj",
    title: "CEO,",
    company: "Jumia Nigeria",
    image: "assets/images/speakers/sunil-natraj.png",
    linkedIn: "#",
  },
  {
    name: "Ayotunde Alabi",
    title: "CEO,",
    company: "Luno Nigeria",
    image: "assets/images/speakers/ayotunde-alabi.jpg",
    linkedIn: "#",
  },
  {
    name: "Lamide Akinola",
    title: "General Manager,",
    company: "Glovo Nigeria",
    image: "assets/images/speakers/lamide-akinola.jpg",
    linkedIn: "#",
  },
  {
    name: "Bidemi Oke",
    title: "CEO,",
    company: "FlashChange",
    image: "assets/images/speakers/bidemi-oke.jpg",
    linkedIn: "#",
  },
  {
    name: "Adekanbi Oluwaseun",
    title: "Growth Lead,",
    company: "Cleva",
    image: "assets/images/speakers/adekanbi-oluwaseun.jpg",
    linkedIn: "#",
  },
  {
    name: "Ayo Adewuyi",
    title: "Head of Product,",
    company: "Prestmit",
    image: "assets/images/speakers/ayo-adewuyi.jpg",
    linkedIn: "#",
  },
  {
    name: "Ashley Immanuel",
    title: "Co-Founder/COO,",
    company: "Semicolon",
    image: "assets/images/speakers/ashley-immanuel.jpg",
    linkedIn: "#",
  },
  {
    name: "Khalil Suleiman Halilu",
    title: "EVC/CEO,",
    company:
      "National Agency for Science and Engineering Infrastructure (NASENI)",
    image: "assets/images/speakers/khalil-suleiman.jpg",
    linkedIn: "#",
  },
  {
    name: "Chidera Amuta",
    title: "Marketing Manager,",
    company: "Vendorcredit Limited",
    image: "assets/images/speakers/chidera-amuta.jpg",
    linkedIn: "#",
  },
  {
    name: "Oluseye Seton",
    title: "Chief Growth Officer,",
    company: "Vendorcredit Limited",
    image: "assets/images/speakers/oluseye-seton.png",
    linkedIn: "#",
  },
  {
    name: "Preston Ideh ",
    title: "Co-founder & CEO,",
    company: "Stears",
    image: "assets/images/speakers/preston-ideh.jpg",
    linkedIn: "#",
  },
  {
    name: "Dapo Salami",
    title: "Managing Director/CEO,",
    company: "Platview Technologies",
    image: "assets/images/speakers/dapo-salami.jpg",
    linkedIn: "#",
  },
  {
    name: "Tolu Osho",
    title: "CEO & Co-Founder,",
    company: "Pesa",
    image: "assets/images/speakers/tolu-osho.jpg",
    linkedIn: "#",
  },
  {
    name: "Dr Ayotunder Coker",
    title: "CEO,",
    company: "OADC",
    image: "assets/images/speakers/ayotunde-coker.jpg",
    linkedIn: "#",
  },
  {
    name: "Goodness Okpani",
    title: "Chief Solutions Architect,",
    company: "Ethnos Cyber LTD",
    image: "assets/images/speakers/goodness-okpani.jpg",
    linkedIn: "#",
  },
  {
    name: "Ayo Oyaleke",
    title: "Co-founder and CEO,",
    company: "Mainstack",
    image: "assets/images/speakers/ayo-oyaleke.jpg",
    linkedIn: "#",
  },
  {
    name: "Nana Aisha Salaudeen",
    title: "Managing Editor,",
    company: "Paystack",
    image: "assets/images/speakers/nana-aisha.jpg",
    linkedIn: "#",
  },
  {
    name: "Yemi Keri",
    title: "CEO,",
    company: "Heckerbella",
    image: "assets/images/speakers/yemi-keri.jpg",
    linkedIn: "#",
  },
  {
    name: "Mfonobong Umana",
    title: "Product Lead,",
    company: "Human Capital Matrix",
    image: "assets/images/speakers/mfonobong-umana.jpg",
    linkedIn: "#",
  },
  {
    name: "Omolara Dada",
    title: "Growth & Marketing Lead,",
    company: "Anchor",
    image: "assets/images/speakers/omolara-dada.jpg",
    linkedIn: "#",
  },
  {
    name: "Ngozi Chukwu",
    title: "Reporter,",
    company: "TechCabal",
    image: "assets/images/speakers/ngozi-chukwu.png",
    linkedIn: "#",
  },
  {
    name: "Onothoja Ogheneruona (Ron)",
    title: "Director of Product,",
    company: "Juicyway",
    image: "assets/images/speakers/onothoja.png",
    linkedIn: "#",
  },
  {
    name: "Benjy Feinberg",
    title: "Founder/CEO,",
    company: "Cedar Money",
    image: "assets/images/speakers/benjy-feinberg.jpg",
    linkedIn: "#",
  },
  {
    name: "Boluwatife Akande",
    title: "Senior Research Analyst,",
    company: "Busha",
    image: "assets/images/speakers/boluwatife-akande.jpg",
    linkedIn: "#",
  },
  {
    name: "Dr Krishnan Ranganath",
    title: "Regional Executive,",
    company: "Africa Data Center",
    image: "assets/images/speakers/dr-krish-ranganath.jpg",
    linkedIn: "#",
  },
  {
    name: "Ebuka Arinze",
    title: "Chief Product Officer,",
    company: "Kredete",
    image: "assets/images/speakers/ebuka-arinze.jpg",
    linkedIn: "#",
  },
  {
    name: "Rosemond Phil-Othihiwa",
    title: "Senior Legal Counsel (Africa), Legal, Compliance and Risk,",
    company: "Alx Africa",
    image: "assets/images/speakers/rosemond-phil.jpg",
    linkedIn: "#",
  },
  {
    name: "Ike Ekemah",
    title: "Marketing & Communications Manager,",
    company: "Zabira Technologies",
    image: "assets/images/speakers/ike-ekemah.jpg",
    linkedIn: "#",
  },
  {
    name: "Olusola Olakanmi",
    title: "Vice President, Account Management, West Africa,",
    company: "Mastercard",
    image: "assets/images/speakers/olusola-olakanmi.jpg",
    linkedIn: "#",
  },
  {
    name: "Oluwatoni Ajewole",
    title: "Recruitment and Activation Specialist,",
    company: "ALX",
    image: "assets/images/speakers/oluwatoni-ajewole.jpg",
    linkedIn: "#",
  },
  {
    name: "Jennie Nwokoye",
    title: "CEO,",
    company: "Clafiya",
    image: "assets/images/speakers/jennie-nwokoye.jpg",
    linkedIn: "#",
  },
  {
    name: "Francis Siru",
    title: "Programme Director, 3MTT Adviser,",
    company: "HMFCIDE",
    image: "assets/images/speakers/francis-siru.jpg",
    linkedIn: "#",
  },
  {
    name: "Jennifer Omame",
    title: "Assistant Vice President Product,",
    company: "Parthian Partners",
    image: "assets/images/speakers/jennifer-omame.jpg",
    linkedIn: "#",
  },
  {
    name: "Adejoke Haastrup",
    title: "Developer Relations Lead,",
    company: "ALATPay",
    image: "assets/images/speakers/adejoke-haastrup.jpg",
    linkedIn: "#",
  },
  {
    name: "Fiyin Ogunlesi",
    title: "Managing Principal,",
    company: "TAG Africa",
    image: "assets/images/speakers/fiyin-ogunlesi.jpg",
    linkedIn: "#",
  },
  {
    name: "Oluwadara Openiyi",
    title: "Product Manager,",
    company: "Busha",
    image: "assets/images/speakers/oluwadara-openiyi.jpg",
    linkedIn: "#",
  },
  {
    name: "Oreoluwa Boboye",
    title: "Managing Director/CEO,",
    company: "Jobberman Nigeria",
    image: "assets/images/speakers/oreoluwa-boboye.jpg",
    linkedIn: "#",
  },
  {
    name: "Olawale Adegoke",
    title: "CEO,",
    company: "Nimbus Media",
    image: "assets/images/speakers/olawale-adegoke.jpg",
    linkedIn: "#",
  },
  {
    name: "Oluwadunni Fanibe",
    title: "Accelerator Portfolio Manager,",
    company: "Google for Startups, SSA",
    image: "assets/images/speakers/oluwadunni-fanibe.jpg",
    linkedIn: "#",
  },
  {
    name: "Lehlé Baldé",
    title: "Media Executive/Financial Inclusion Advocate,",
    company: "",
    image: "assets/images/speakers/lehle-balde.jpg",
    linkedIn: "#",
  },
  {
    name: "Gold Sylvester",
    title: "CEO,",
    company: "Traddify",
    image: "assets/images/speakers/gold-sylvester.jpg",
    linkedIn: "#",
  },
  {
    name: "Daniel Adeyemi",
    title: "Managing Editor,",
    company: "Condia",
    image: "assets/images/speakers/daniel-adeyemi.jpg",
    linkedIn: "#",
  },
  {
    name: "Ale Daniel",
    title: "Group CTO, Capital Sage |",
    company: "MD, ERCAS",
    image: "assets/images/speakers/ale-daniel.jpg",
    linkedIn: "#",
  },
  {
    name: "Olumide Okubadejo, PhD",
    title: "Head of Product,",
    company: "Sabi ",
    image: "assets/images/speakers/olumide-okubadejo.jpg",
    linkedIn: "#",
  },
  {
    name: "Reni Onafeko",
    title: "Chief Growth Officer,",
    company: "Glovo Nigeria",
    image: "assets/images/speakers/reni-onafeko.jpg",
    linkedIn: "#",
  },
];

const attSlideOne = [
  "assets/images/sponsors/mastercard.png",
  "assets/images/sponsors/up.jpg",
  "assets/images/sponsors/interswitch.png",
  "assets/images/sponsors/9psb.jpg",
  "assets/images/sponsors/dpopay.png",
  "assets/images/sponsors/palmpay.png",
  "assets/images/sponsors/zoho.jpg",
  "assets/images/sponsors/vfd.png",
  "assets/images/sponsors/octa.png",
  "assets/images/sponsors/freshworks.png",
  "assets/images/sponsors/rackcenter.jpg",
  "assets/images/sponsors/moniepoint.png",
  "assets/images/sponsors/maplerad.png",
  "assets/images/sponsors/payaza.png",
  "assets/images/sponsors/termii.png",
  "assets/images/sponsors/uber.png",
  "assets/images/sponsors/yellowcard.png",
  "assets/images/sponsors/qwid.png",
  "assets/images/sponsors/cleva.jpg",
];

const attSlideTwo = [
  // Anchoria,
  "assets/images/sponsors/bitmama.png",
  // Servercore,
  "assets/images/sponsors/bolt.png",
  "assets/images/sponsors/zone.jpg",
  "assets/images/sponsors/identitypass.png",
  // Migo,
  "assets/images/sponsors/scrella.png",
  "assets/images/sponsors/africastalking.png",
  "assets/images/sponsors/anchor.jpg",
  "assets/images/sponsors/i-invest.jpg",

  "assets/images/sponsors/cellulant.jpg",
  "assets/images/sponsors/scalex.png",
  // Mycover,
  // InfoBip
  "assets/images/sponsors/zitra.png",
  "assets/images/sponsors/ami.png",
  "assets/images/sponsors/nownow.png",
  "assets/images/sponsors/credo.jpg",
  "assets/images/sponsors/flincap.png",
  "assets/images/sponsors/seerbit.png",
  "assets/images/sponsors/alx.png",
  "assets/images/sponsors/pocketfood.jpg",
];

const attSlideThree = [
  "assets/images/sponsors/ayo.jpg",
  "assets/images/sponsors/africadate.jpg",
  "assets/images/sponsors/zerocomplex.png",
  "assets/images/sponsors/flick.png",
  "assets/images/sponsors/garamart.jpg",
  "assets/images/sponsors/prembly.jpg",
  "assets/images/sponsors/chamsaccess.jpg",
  "assets/images/sponsors/bunce.png",
  "assets/images/sponsors/3line.png",
  "assets/images/sponsors/turaco.png",
  "assets/images/sponsors/fifthlab.png",
  "assets/images/sponsors/arca.jpg",
  "assets/images/sponsors/upperlink.jpg",
  "assets/images/sponsors/pfs.jpg",
  "assets/images/sponsors/furex.png",
  "assets/images/sponsors/cent.png",
  "assets/images/sponsors/inlaks.png",
  "assets/images/sponsors/shortlet.png",
];

const sponsorSlideOne = [
  "/assets/images/sponsor25/accrue.png",
  "/assets/images/sponsor25/advansiosticky.png",
  "/assets/images/sponsor25/alatpay.png",
  "/assets/images/sponsor25/alx.png",
  "/assets/images/sponsor25/apex.svg",
  "/assets/images/sponsor25/atradio.jpg",
  "/assets/images/sponsor25/axia.png",
  "/assets/images/sponsor25/backend.jpg",
  "/assets/images/sponsor25/busha.png",
  "/assets/images/sponsor25/capitalsage.jpg",
  "/assets/images/sponsor25/cedar.png",
  "/assets/images/sponsor25/cleva-banking.svg",
  "/assets/images/sponsor25/condia.png",
  "/assets/images/sponsor25/cornerstone-ins.png",
  "/assets/images/sponsor25/covr.png",
  "/assets/images/sponsor25/edoigiawerie.jpg",
  "/assets/images/sponsor25/ethnos.png",
  "/assets/images/sponsor25/ffnews.jpg",
  "/assets/images/sponsor25/flashchange.svg",
  "/assets/images/sponsor25/flick.png",
  "/assets/images/sponsor25/cedar.png",
  "/assets/images/sponsor25/hardebs.png",
  "/assets/images/sponsor25/hcmatrix.webp",
  "/assets/images/sponsor25/hydrogen.jpg",
  "/assets/images/sponsor25/i-invest.svg",
  "/assets/images/sponsor25/impacthub.png",
  "/assets/images/sponsor25/jobberman.svg",
  "/assets/images/sponsor25/juicyway.png",
  "/assets/images/sponsor25/kredete.png",
  "/assets/images/sponsor25/luno.png",
  "/assets/images/sponsor25/mainstack.jpg",
  "/assets/images/sponsor25/mastercard.svg",
  "/assets/images/sponsor25/naijapreneur.png",
  "/assets/images/sponsor25/openaccesss-datacenter.png",
  "/assets/images/sponsor25/pay4it.png",
  "/assets/images/sponsor25/pesa.svg",
  "/assets/images/sponsor25/platview.png",
  "/assets/images/sponsor25/pocketfood.jpg",
  "/assets/images/sponsor25/prestmit.svg",
  "/assets/images/sponsor25/pulse.png",
  "/assets/images/sponsor25/regtech.png",
  "/assets/images/sponsor25/remoteworkerhr.png",
  "/assets/images/sponsor25/revwit.svg",
  "/assets/images/sponsor25/startupgrind.svg",
  "/assets/images/sponsor25/sysserve.png",
  "/assets/images/sponsor25/techcabal.png",
  "/assets/images/sponsor25/termii.png",
  "/assets/images/sponsor25/traddify.png",
  "/assets/images/sponsor25/vendorcredit.png",
  "/assets/images/sponsor25/yellowlyfe.png",
  "/assets/images/sponsor25/zabira.png",
  "/assets/images/sponsor25/zedi.png",
  "/assets/images/sponsor25/zexprwire-.png",
  "/assets/images/sponsor25/zitra.png",
  "/assets/images/sponsor25/zoho.svg",
];

const sponsorSlideTwo = [
  "/assets/images/sponsor25/accrue.png",
  "/assets/images/sponsor25/advansiosticky.png",
  "/assets/images/sponsor25/alatpay.png",
  "/assets/images/sponsor25/alx.png",
  "/assets/images/sponsor25/apex.svg",
  "/assets/images/sponsor25/atradio.jpg",
  "/assets/images/sponsor25/axia.png",
  "/assets/images/sponsor25/backend.jpg",
  "/assets/images/sponsor25/busha.png",
  "/assets/images/sponsor25/capitalsage.jpg",
  "/assets/images/sponsor25/cedar.png",
  "/assets/images/sponsor25/cleva-banking.svg",
  "/assets/images/sponsor25/condia.png",
  "/assets/images/sponsor25/cornerstone-ins.png",
  "/assets/images/sponsor25/covr.png",
  "/assets/images/sponsor25/edoigiawerie.jpg",
  "/assets/images/sponsor25/ethnos.png",
  "/assets/images/sponsor25/ffnews.jpg",
  "/assets/images/sponsor25/flashchange.svg",
  "/assets/images/sponsor25/flick.png",
  "/assets/images/sponsor25/cedar.png",
  "/assets/images/sponsor25/hardebs.png",
  "/assets/images/sponsor25/hcmatrix.webp",
  "/assets/images/sponsor25/hydrogen.jpg",
  "/assets/images/sponsor25/i-invest.svg",
  "/assets/images/sponsor25/impacthub.png",
  "/assets/images/sponsor25/jobberman.svg",
  "/assets/images/sponsor25/juicyway.png",
  "/assets/images/sponsor25/kredete.png",
  "/assets/images/sponsor25/luno.png",
  "/assets/images/sponsor25/mainstack.jpg",
  "/assets/images/sponsor25/mastercard.svg",
  "/assets/images/sponsor25/naijapreneur.png",
  "/assets/images/sponsor25/openaccesss-datacenter.png",
  "/assets/images/sponsor25/pay4it.png",
  "/assets/images/sponsor25/pesa.svg",
  "/assets/images/sponsor25/platview.png",
  "/assets/images/sponsor25/pocketfood.jpg",
  "/assets/images/sponsor25/prestmit.svg",
  "/assets/images/sponsor25/pulse.png",
  "/assets/images/sponsor25/regtech.png",
  "/assets/images/sponsor25/remoteworkerhr.png",
  "/assets/images/sponsor25/revwit.svg",
  "/assets/images/sponsor25/startupgrind.svg",
  "/assets/images/sponsor25/sysserve.png",
  "/assets/images/sponsor25/techcabal.png",
  "/assets/images/sponsor25/termii.png",
  "/assets/images/sponsor25/traddify.png",
  "/assets/images/sponsor25/vendorcredit.png",
  "/assets/images/sponsor25/yellowlyfe.png",
  "/assets/images/sponsor25/zabira.png",
  "/assets/images/sponsor25/zedi.png",
  "/assets/images/sponsor25/zexprwire-.png",
  "/assets/images/sponsor25/zitra.png",
  "/assets/images/sponsor25/zoho.svg",
];

const sponsorSlideThree = [
  "/assets/images/sponsor25/accrue.png",
  "/assets/images/sponsor25/advansiosticky.png",
  "/assets/images/sponsor25/alatpay.png",
  "/assets/images/sponsor25/alx.png",
  "/assets/images/sponsor25/apex.svg",
  "/assets/images/sponsor25/atradio.jpg",
  "/assets/images/sponsor25/axia.png",
  "/assets/images/sponsor25/backend.jpg",
  "/assets/images/sponsor25/busha.png",
  "/assets/images/sponsor25/capitalsage.jpg",
  "/assets/images/sponsor25/cedar.png",
  "/assets/images/sponsor25/cleva-banking.svg",
  "/assets/images/sponsor25/condia.png",
  "/assets/images/sponsor25/cornerstone-ins.png",
  "/assets/images/sponsor25/covr.png",
  "/assets/images/sponsor25/edoigiawerie.jpg",
  "/assets/images/sponsor25/ethnos.png",
  "/assets/images/sponsor25/ffnews.jpg",
  "/assets/images/sponsor25/flashchange.svg",
  "/assets/images/sponsor25/flick.png",
  "/assets/images/sponsor25/cedar.png",
  "/assets/images/sponsor25/hardebs.png",
  "/assets/images/sponsor25/hcmatrix.webp",
  "/assets/images/sponsor25/hydrogen.jpg",
  "/assets/images/sponsor25/i-invest.svg",
  "/assets/images/sponsor25/impacthub.png",
  "/assets/images/sponsor25/jobberman.svg",
  "/assets/images/sponsor25/juicyway.png",
  "/assets/images/sponsor25/kredete.png",
  "/assets/images/sponsor25/luno.png",
  "/assets/images/sponsor25/mainstack.jpg",
  "/assets/images/sponsor25/mastercard.svg",
  "/assets/images/sponsor25/naijapreneur.png",
  "/assets/images/sponsor25/openaccesss-datacentre.png",
  "/assets/images/sponsor25/pay4it.png",
  "/assets/images/sponsor25/pesa.svg",
  "/assets/images/sponsor25/platview.png",
  "/assets/images/sponsor25/pocketfood.jpg",
  "/assets/images/sponsor25/prestmit.svg",
  "/assets/images/sponsor25/pulse.png",
  "/assets/images/sponsor25/regtech.png",
  "/assets/images/sponsor25/remoteworkerhr.png",
  "/assets/images/sponsor25/revwit.svg",
  "/assets/images/sponsor25/startupgrind.svg",
  "/assets/images/sponsor25/sysserve.png",
  "/assets/images/sponsor25/techcabal.png",
  "/assets/images/sponsor25/termii.png",
  "/assets/images/sponsor25/traddify.png",
  "/assets/images/sponsor25/vendorcredit.png",
  "/assets/images/sponsor25/yellowlyfe.png",
  "/assets/images/sponsor25/zabira.png",
  "/assets/images/sponsor25/zedi.png",
  "/assets/images/sponsor25/zexprwire-.png",
  "/assets/images/sponsor25/zitra.png",
  "/assets/images/sponsor25/zoho.svg",
];
