const speakers = [
  {
    name: "Folasade Femi-Lawal",
    title: "Country Manager, West Africa,",
    company: "Mastercard",
    image: "assets/images/speakers/folasade.jpg",
    linkedIn: "#",
  },
  {
    name: "Kehinde Ogundare",
    title: "Country Manager, Nigeria,",
    company: "Zoho",
    image: "assets/images/speakers/kehinde-ogundare.jpg",
    linkedIn: "#",
  },
  {
    name: "Tolu Alabi",
    title: "CEO",
    company: "Cleva Banking",
    image: "assets/images/speakers/tolu-alabi.jpg",
    linkedIn: "#",
  },
  {
    name: "Tolulope A. Adeyinka",
    title: "Fintech Business Development Lead,",
    company: "Mastercard, West Africa",
    image: "assets/images/speakers/tolulope-adeyinka.jpg",
    linkedIn: "#",
  },
  {
    name: "Yewande Adewusi",
    title: "Chief Operating Officer,",
    company: "Alitheia Capital",
    image: "assets/images/speakers/yewande-adewusi.jpg",
    linkedIn: "#",
  },
  {
    name: "Dr Dotun Olowoporoku",
    title: "Managing Partner,",
    company: "Ventures Platform",
    image: "assets/images/speakers/dotun-olowo.jpg",
    linkedIn: "#",
  },
  {
    name: "Satoshi Shinada",
    title: "Partner,",
    company: "Verod-Kepple Africa Ventures",
    image: "assets/images/speakers/satoshi-shinada.jpg",
    linkedIn: "#",
  },
  {
    name: "Olu Oyinsan",
    title: "Managing Partner,",
    company: "Oui Capital",
    image: "assets/images/speakers/olu-oyinsan.jpg",
    linkedIn: "#",
  },
  {
    name: "Babatunde Obadero",
    title: "Chief Executive Officer,",
    company: "Zitra",
    image: "assets/images/speakers/babatunde-obadero.jpg",
    linkedIn: "#",
  },
  {
    name: "Babajide Duroshola",
    title: "General Manager, Nigeria,",
    company: "M-Kopa",
    image: "assets/images/speakers/babajide-duroshola.jpg",
    linkedIn: "#",
  },
  {
    name: "Fola Olatunji-David",
    title: "Founding Partner,",
    company: "Kickoff Africa",
    image: "assets/images/speakers/fola-olatunji.png",
    linkedIn: "#",
  },
  {
    name: "Olawale Samuel",
    title: "CEO,",
    company: "Axia Africa",
    image: "assets/images/speakers/olawale-olakanmi.jpg",
    linkedIn: "#",
  },
  {
    name: "Sunil Natraj",
    title: "CEO,",
    company: "Jumia Nigeria",
    image: "assets/images/speakers/sunil-natraj.png",
    linkedIn: "#",
  },
  {
    name: "Ayotunde Alabi",
    title: "CEO,",
    company: "Luno Nigeria",
    image: "assets/images/speakers/ayotunde-alabi.jpg",
    linkedIn: "#",
  },
  {
    name: "Lamide Akinola",
    title: "General Manager,",
    company: "Glovo Nigeria",
    image: "assets/images/speakers/lamide-akinola.jpg",
    linkedIn: "#",
  },
  {
    name: "Bidemi Oke",
    title: "CEO,",
    company: "FlashChange",
    image: "assets/images/speakers/bidemi-oke.jpg",
    linkedIn: "#",
  },
  {
    name: "Adekanbi Oluwaseun",
    title: "Growth Lead,",
    company: "Cleva",
    image: "assets/images/speakers/adekanbi-oluwaseun.jpg",
    linkedIn: "#",
  },
  {
    name: "Ayo Adewuyi",
    title: "Head of Product,",
    company: "Prestmit",
    image: "assets/images/speakers/ayo-adewuyi.jpg",
    linkedIn: "#",
  },
  {
    name: "Ashley Immanuel",
    title: "Co-Founder/COO,",
    company: "Semicolon",
    image: "assets/images/speakers/ashley-immanuel.jpg",
    linkedIn: "#",
  },
  {
    name: "Khalil Suleiman Halilu",
    title: "EVC/CEO,",
    company:
      "National Agency for Science and Engineering Infrastructure (NASENI)",
    image: "assets/images/speakers/khalil-suleiman.jpg",
    linkedIn: "#",
  },
  {
    name: "Chidera Amuta",
    title: "Marketing Manager,",
    company: "Vendorcredit Limited",
    image: "assets/images/speakers/chidera-amuta.jpg",
    linkedIn: "#",
  },
  {
    name: "Oluseye Seton",
    title: "Chief Growth Officer,",
    company: "Vendorcredit Limited",
    image: "assets/images/speakers/oluseye-seton.png",
    linkedIn: "#",
  },
  {
    name: "Preston Ideh ",
    title: "Co-founder & CEO,",
    company: "Stears",
    image: "assets/images/speakers/preston-ideh.jpg",
    linkedIn: "#",
  },
  {
    name: "Dapo Salami",
    title: "Managing Director/CEO,",
    company: "Platview Technologies",
    image: "assets/images/speakers/dapo-salami.jpg",
    linkedIn: "#",
  },
];

const box1Images = [
  "/assets/images/highlights/1.jpg",
  "/assets/images/highlights/11.jpg",
  "/assets/images/highlights/13.jpg",
  "/assets/images/highlights/29.jpg",
  "/assets/images/highlights/22.jpg",
  "/assets/images/highlights/24.jpg",
  "/assets/images/highlights/27.jpg",
  "/assets/images/highlights/30.jpg",
  "/assets/images/highlights/18.jpg",
  "/assets/images/highlights/20.jpg",
  "/assets/images/highlights/16.jpg",
];

const box2Images = [
  "/assets/images/highlights/17.jpg",
  "/assets/images/highlights/4.jpg",
  "/assets/images/highlights/26.jpg",
  "/assets/images/highlights/25.jpg",
  "/assets/images/highlights/12.jpg",
  "/assets/images/highlights/14.jpg",
  "/assets/images/highlights/28.jpg",
  "/assets/images/highlights/15.jpg",
  "/assets/images/highlights/23.jpg",
  "/assets/images/highlights/21.jpg",
  "/assets/images/highlights/7.jpg",
];

const sponsorsSlideOne = [
  "assets/images/sponsors/mastercard.png",
  "assets/images/sponsors/up.jpg",
  "assets/images/sponsors/interswitch.png",
  "assets/images/sponsors/9psb.jpg",
  "assets/images/sponsors/dpopay.png",
  "assets/images/sponsors/palmpay.png",
  "assets/images/sponsors/zoho.jpg",
  "assets/images/sponsors/vfd.png",
  "assets/images/sponsors/octa.png",
  "assets/images/sponsors/freshworks.png",
  "assets/images/sponsors/rackcenter.jpg",
  "assets/images/sponsors/moniepoint.png",
  "assets/images/sponsors/maplerad.png",
  "assets/images/sponsors/payaza.png",
  "assets/images/sponsors/termii.png",
  "assets/images/sponsors/uber.png",
  "assets/images/sponsors/yellowcard.png",
  "assets/images/sponsors/qwid.png",
  "assets/images/sponsors/cleva.jpg",
  // Anchoria,
  "assets/images/sponsors/bitmama.png",
  // Servercore,
  "assets/images/sponsors/bolt.png",
  "assets/images/sponsors/zone.jpg",
  "assets/images/sponsors/identitypass.png",
  // Migo,
  "assets/images/sponsors/scrella.png",
  "assets/images/sponsors/africastalking.png",
  "assets/images/sponsors/anchor.jpg",
  "assets/images/sponsors/i-invest.jpg",
];

const sposnorsSlideTwo = [
  "assets/images/sponsors/cellulant.jpg",
  "assets/images/sponsors/scalex.png",
  // Mycover,
  // InfoBip
  "assets/images/sponsors/zitra.png",
  "assets/images/sponsors/ami.png",
  "assets/images/sponsors/nownow.png",
  "assets/images/sponsors/credo.jpg",
  "assets/images/sponsors/flincap.png",
  "assets/images/sponsors/seerbit.png",
  "assets/images/sponsors/alx.png",
  "assets/images/sponsors/pocketfood.jpg",
  "assets/images/sponsors/ayo.jpg",
  "assets/images/sponsors/africadate.jpg",
  "assets/images/sponsors/zerocomplex.png",
  "assets/images/sponsors/flick.png",
  "assets/images/sponsors/garamart.jpg",
  "assets/images/sponsors/prembly.jpg",
  "assets/images/sponsors/chamsaccess.jpg",
  "assets/images/sponsors/bunce.png",
  "assets/images/sponsors/3line.png",
  "assets/images/sponsors/turaco.png",
  "assets/images/sponsors/fifthlab.png",
  "assets/images/sponsors/arca.jpg",
  "assets/images/sponsors/upperlink.jpg",
  "assets/images/sponsors/pfs.jpg",
  "assets/images/sponsors/furex.png",
  "assets/images/sponsors/cent.png",
  "assets/images/sponsors/inlaks.png",
  "assets/images/sponsors/shortlet.png",
];
