const speakers = [
  {
    name: "Ogunniran Hakeem",
    title: "CEO, Eximia Realty, Chairman of Board,",
    company: "Lagos Building Investment Company PLC",
    image: "assets/images/speakers/ogunniran-hakeem.png",
    linkedIn: "#",
  },
  {
    name: "Derrick Roper",
    title: "CEO,",
    company: "Novare Equity Partners",
    image: "assets/images/speakers/derrick-roper.png",
    linkedIn: "#",
  },
  {
    name: "Saadiyah Aliyu",
    title: "CEO,",
    company: "Urban Shelters",
    image: "assets/images/speakers/saadiyah-aliyu.png",
    linkedIn: "#",
  },
  {
    name: "Azubike Emodi",
    title: "CEO,",
    company: "Afriland Properties",
    image: "assets/images/speakers/azubike-emodi.png",
    linkedIn: "#",
  },
  {
    name: "Bright Okereke",
    title: "COO,",
    company: "Flinx Realty",
    image: "assets/images/speakers/bright-okereke.png",
    linkedIn: "#",
  },
  {
    name: "Bolanle Ibitola",
    title: "CEO,",
    company: "Crayon Developments",
    image: "assets/images/speakers/bolanle-ibitola.png",
    linkedIn: "#",
  },
  {
    name: "Jamila Faniyi",
    title: "CEO,",
    company: "M & E Kaiser",
    image: "assets/images/speakers/jamila-faniyi.png",
    linkedIn: "#",
  },
  {
    name: "Frank Okosun",
    title: "Senior Partner,",
    company: "Knight Frank Nigeria",
    image: "assets/images/speakers/frank-okosun.png",
    linkedIn: "#",
  },
  {
    name: "Louis Ogbeifun",
    title: "Chief Investment Officer,",
    company: "Total E&P Pension Fund Nigeria",
    image: "assets/images/speakers/louis-ogbeifun.png",
    linkedIn: "#",
  },
  {
    name: "Woye Famojuro",
    title: "Managing Partner,",
    company: "Tide Legal Partners",
    image: "assets/images/speakers/woye-famojuro.png",
    linkedIn: "#",
  },
  {
    name: "Dr Ayo Alo",
    title: "CEO,",
    company: "Axial Pacific",
    image: "assets/images/speakers/dr-ayo-alo.png",
    linkedIn: "#",
  },
  {
    name: "Oyindamola Bode-Olumodeji",
    title: "CEO,",
    company: "Seza Pro",
    image: "assets/images/speakers/oyindamola-bode-olumodeji.png",
    linkedIn: "#",
  },
  {
    name: "Ejide Akinbiyi",
    title: "Co-Founder,",
    company: "MaterialsPro",
    image: "assets/images/speakers/ejide-akinbiyi.png",
    linkedIn: "#",
  },
  {
    name: "Akpor Ikogho",
    title: "Managing Partner,",
    company: "Mark Renee Legal Partners",
    image: "assets/images/speakers/akpor-ikogho.png",
    linkedIn: "#",
  },
  {
    name: "Dr Munachino Eze",
    title: "Chairman,",
    company: "Millinium Group",
    image: "assets/images/speakers/dr-munachinoe-eze.png",
    linkedIn: "#",
  },
  {
    name: "Paul Foh",
    title: "CEO,",
    company: "Sales Factory Global",
    image: "assets/images/speakers/paul-foh.png",
    linkedIn: "#",
  },
  {
    name: "Eizu Uwaoma",
    title: "CEO,",
    company: "Hexavia Group",
    image: "assets/images/speakers/eizu-uwaoma.png",
    linkedIn: "#",
  },
];

const attSlideOne = [
  "assets/images/sponsors/octo5.png",
  "assets/images/sponsors/flinx.png",
  "assets/images/sponsors/facibus.png",
  "assets/images/sponsors/pinnacleprime.png",
  "assets/images/sponsors/updc.png",
  "assets/images/sponsors/cutstruct.png",
  "assets/images/sponsors/abbey.png",
  "assets/images/sponsors/joe.png",
  "assets/images/sponsors/novare.png",
  "assets/images/sponsors/periwinkle.png",
  "assets/images/sponsors/finebricks.png",
  "assets/images/sponsors/rebar.png",
  "assets/images/sponsors/urbanshelter.png",
  "assets/images/sponsors/gridcrux.png",
  "assets/images/sponsors/bedrock.png",
  "assets/images/sponsors/butletlive.png",
  "assets/images/sponsors/noblegrounds.png",
];

const attSlideTwo = [
  "assets/images/sponsors/meristem.png",
  "assets/images/sponsors/cobblestone.png",
  "assets/images/sponsors/polymath.png",
  "assets/images/sponsors/bujeti.png",
  "assets/images/sponsors/flowmono.png",
  "assets/images/sponsors/flick.png",
  "assets/images/sponsors/uvest.png",
  "assets/images/sponsors/crayon.png",
  "assets/images/sponsors/materialspro.png",
  "assets/images/sponsors/alphacrux.png",
  "assets/images/sponsors/sesoglobal.png",
  "assets/images/sponsors/realtyreport.png",
  "assets/images/sponsors/nimbus.png",
  "assets/images/sponsors/venco.png",
  "assets/images/sponsors/greenkey.png",
  "assets/images/sponsors/strongmas.png",
  "assets/images/sponsors/stonetrust.png",
  "assets/images/sponsors/infinitytrust.png",
];

const attSlideThree = [
  "assets/images/sponsors/octo5.png",
  "assets/images/sponsors/flinx.png",
  "assets/images/sponsors/facibus.png",
  "assets/images/sponsors/updc.png",
  "assets/images/sponsors/cutstruct.png",
  "assets/images/sponsors/rebar.png",
  "assets/images/sponsors/urbanshelter.png",
  "assets/images/sponsors/pinnacleprime.png",
  "assets/images/sponsors/abbey.png",
  "assets/images/sponsors/joe.png",
  "assets/images/sponsors/novare.png",
  "assets/images/sponsors/periwinkle.png",
  "assets/images/sponsors/finebricks.png",
  "assets/images/sponsors/gridcrux.png",
  "assets/images/sponsors/bedrock.png",
  "assets/images/sponsors/noblegrounds.png",
  "assets/images/sponsors/cobblestone.png",
  "assets/images/sponsors/polymath.png",
];
